version: '3'

services:
    nginx:
        container_name: collection-manager-nginx
        build: ./docker/prod/nginx
        ports:
            - 8081:80
        volumes:
            - app_data:/var/www/html
        networks:
            - default

    app:
        container_name: collection-manager-app
        image: collection-manager:latest
        volumes:
            - app_data:/var/www/html
        networks:
            - default

    db:
        container_name: collection-manager-db
        image: mariadb:latest
        environment:
            - MYSQL_ROOT_PASSWORD=collectionManager
            - MYSQL_USER=collectionManager
            - MYSQL_PASSWORD=collectionManager
            - MYSQL_DATABASE=collectionManager
        ports:
            - 3307:3306
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - default

    es1:
        container_name: collection-manager-elasticsearch-1
        build: ./docker/prod/elasticsearch
        environment:
            - cluster.name=collection-manager-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - es1_data:/usr/share/elasticsearch/data
        networks:
            - default

    es2:
        container_name: collection-manager-elasticsearch-2
        build: ./docker/prod/elasticsearch
        environment:
            - cluster.name=collection-manager-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "discovery.zen.ping.unicast.hosts=es1"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - es2_data:/usr/share/elasticsearch/data
        networks:
            - default

volumes:
    db_data:
        driver: local
    es1_data:
        driver: local
    es2_data:
        driver: local
    app_data:
        driver: local

networks:
    default:
