imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: elasticsearch.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          '%env(SYMFONY_SECRET)%'
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - form/fields.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Doctrine extensions
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true
            blameable: true
            tree: true

# Doctrine migration
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

# Swiftmailer Configuration
swiftmailer:
    url: '%env(MAILER_URL)%'
    spool:     { type: memory }

# ReCaptcha
ewz_recaptcha:
    public_key:  '%env(RECAPTCHA_PUBLIC_KEY)%'
    private_key: '%env(RECAPTCHA_PRIVATE_KEY)%'
    locale_key:  '%kernel.default_locale%'

# Vich uploader
vich_uploader:
    db_driver: orm

    mappings:
        plasmid_file:
            uri_prefix:         /protected-files/plasmids # Use /protected-files to serve it with X-Accel-Redirect header
            upload_destination: '%kernel.project_dir%/files/plasmids'
            namer:              vich_uploader.namer_uniqid
        seller_offer:
            uri_prefix:         /protected-files/sellers/offers # Use /protected-files to serve it with X-Accel-Redirect header
            upload_destination: '%kernel.project_dir%/files/sellers/offers'
            namer:              vich_uploader.namer_uniqid
        product_quote:
            uri_prefix:         /protected-files/products/quotes # Use /protected-files to serve it with X-Accel-Redirect header
            upload_destination: '%kernel.project_dir%/files/products/quotes'
            namer:              vich_uploader.namer_uniqid
        product_manual:
            uri_prefix:         /protected-files/products/manuals # Use /protected-files to serve it with X-Accel-Redirect header
            upload_destination: '%kernel.project_dir%/files/products/manuals'
            namer:              vich_uploader.namer_uniqid
