# FOS Elastica Configuration
fos_elastica:
    clients:
        default: { host: search, port: 9200 }
    indexes:
        app:
            client: default
            finder: ~
            settings:
                index:
                    analysis:
                        analyzer:
                            autoName_analyzer:
                                type: standard
                            name_analyzer:
                                type: custom
                                tokenizer: whitespace
                                filter: [lowercase]
            types:
                gmoStrain:
                    mappings:
                        autoName:
                            analyzer :        autoName_analyzer
                            search_analyzer : autoName_analyzer
                        name:
                            analyzer :        name_analyzer
                            search_analyzer : name_analyzer
                        author:
                            property_path:    author.id
                        deleted:
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\GmoStrain
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             ~
                wildStrain:
                    mappings:
                        autoName:
                            analyzer :        autoName_analyzer
                            search_analyzer : autoName_analyzer
                        name:
                            analyzer :        name_analyzer
                            search_analyzer : name_analyzer
                        country:
                        author:
                            property_path:    author.id
                        deleted:
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\WildStrain
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             ~
                plasmid:
                    mappings:
                        autoName:
                            analyzer :        autoName_analyzer
                            search_analyzer : autoName_analyzer
                        name:
                            analyzer :        name_analyzer
                            search_analyzer : name_analyzer
                        team:
                            property_path:    team.id
                        author:
                            property_path:    author.id
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\Plasmid
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             ~
                primer:
                    mappings:
                        autoName:
                            analyzer :        autoName_analyzer
                            search_analyzer : autoName_analyzer
                        name:
                            analyzer :        name_analyzer
                            search_analyzer : name_analyzer
                        team:
                            property_path:    team.id
                        author:
                            property_path:    author.id
                        sequence:
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\Primer
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             ~
