# FOS Elastica Configuration
fos_elastica:
    clients:
        default: { host: search, port: 9200 }
    indexes:
        app:
            client: default
            finder: ~
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_index_analyzer :
                                type     :    custom
                                tokenizer:    nGram
                                #filter   :    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
                                filter   :    [stopwords, asciifolding ,lowercase, worddelimiter]
                            custom_search_analyzer :
                                type     :    custom
                                tokenizer:    standard
                                #filter   :    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
                                filter   :    [stopwords, asciifolding ,lowercase, worddelimiter]
                        tokenizer:
                            nGram:
                                type:     nGram
                                min_gram: 3
                                max_gram: 8
                                token_chars: [letter, digit, whitespace, punctuation, symbol]
                        filter:
                            #snowball:
                            #    type:     snowball
                            #    language: English
                            #elision:
                            #    type:     elision
                            #    articles: [l, m, t, qu, n, s, j, d]
                            stopwords:
                                type:      stop
                                stopwords: [_english_]
                                ignore_case : true
                            worddelimiter :
                                type:      word_delimiter
                                preserve_original: true
            types:
                gmoStrain:
                    mappings:
                        systematicName:
                            boost: 3
                            analyzer : custom_index_analyzer
                            search_analyzer : custom_search_analyzer
                        usualName:
                            analyzer : custom_index_analyzer
                            search_analyzer : custom_search_analyzer
                    persistence:
                      driver: orm
                      model: AppBundle\Entity\GmoStrain
                      provider: ~
                      listener: ~
                      finder: ~
                      repository: AppBundle\SearchRepository\StrainRepository
                wildStrain:
                    mappings:
                        systematicName:
                            boost: 3
                            analyzer : custom_index_analyzer
                            search_analyzer : custom_search_analyzer
                        usualName:
                            analyzer : custom_index_analyzer
                            search_analyzer : custom_search_analyzer
                    persistence:
                      driver: orm
                      model: AppBundle\Entity\WildStrain
                      provider: ~
                      listener: ~
                      finder: ~
                      repository: AppBundle\SearchRepository\StrainRepository
