# FOS Elastica Configuration
fos_elastica:
    clients:
        default: { host: search, port: 9200 }
    indexes:
        app:
            client: default
            finder: ~
            settings:
                index:
                    analysis:
                        analyzer:
                            strain_name_analyzer:
                                type: standard
            types:
                gmoStrain:
                    mappings:
                        systematicName:
                            analyzer :        strain_name_analyzer
                            search_analyzer : strain_name_analyzer
                        usualName:
                            analyzer :        strain_name_analyzer
                            search_analyzer : strain_name_analyzer
                        deleted:
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\GmoStrain
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             AppBundle\SearchRepository\StrainRepository
                wildStrain:
                    mappings:
                        systematicName:
                            analyzer :        strain_name_analyzer
                            search_analyzer : strain_name_analyzer
                        usualName:
                            analyzer :        strain_name_analyzer
                            search_analyzer : strain_name_analyzer
                        country:
                        deleted:
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\WildStrain
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             AppBundle\SearchRepository\StrainRepository
