# FOS Elastica Configuration
fos_elastica:
    clients:
        default: { host: search, port: 9200 }
    indexes:
        app:
            client: default
            finder: ~
            settings:
                index:
                    analysis:
                        analyzer:
                            simple_name_analyzer:
                                type: simple
            types:
                gmoStrain:
                    mappings:
                        systematicName:
                            analyzer :        simple_name_analyzer
                            search_analyzer : simple_name_analyzer
                        usualName:
                            analyzer :        simple_name_analyzer
                            search_analyzer : simple_name_analyzer
                        author:
                            property_path:    author.id
                        deleted:
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\GmoStrain
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             AppBundle\SearchRepository\StrainRepository
                wildStrain:
                    mappings:
                        systematicName:
                            analyzer :        simple_name_analyzer
                            search_analyzer : simple_name_analyzer
                        usualName:
                            analyzer :        simple_name_analyzer
                            search_analyzer : simple_name_analyzer
                        country:
                        author:
                            property_path:    author.id
                        deleted:
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\WildStrain
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             AppBundle\SearchRepository\StrainRepository
                plasmid:
                    mappings:
                        autoName:
                            analyzer :        simple_name_analyzer
                            search_analyzer : simple_name_analyzer
                        name:
                            analyzer :        simple_name_analyzer
                            search_analyzer : simple_name_analyzer
                        team:
                            property_path:    team.id
                        author:
                            property_path:    author.id
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\Plasmid
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             AppBundle\SearchRepository\PlasmidRepository
                primer:
                    mappings:
                        autoName:
                            analyzer :        simple_name_analyzer
                            search_analyzer : simple_name_analyzer
                        name:
                            analyzer :        simple_name_analyzer
                            search_analyzer : simple_name_analyzer
                        team:
                            property_path:    team.id
                        author:
                            property_path:    author.id
                        sequence:
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\Primer
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             AppBundle\SearchRepository\PrimerRepository
