# FOS Elastica Configuration
fos_elastica:
    clients:
        default: { host: search, port: 9200 }
    indexes:
        app:
            client: default
            finder: ~
            settings:
                index:
                    analysis:
                        analyzer:
                            search_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: [standard, lowercase, asciifolding]
                            ngram_index_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: [standard, lowercase, asciifolding, edge_ngram]
                            ngram_sequence_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: [standard, lowercase, asciifolding, sequence_ngram]
                        filter:
                            edge_ngram:
                                type: edgeNGram
                                side: front
                                min_gram: 1
                                max_gram: 20
                            sequence_ngram:
                                type: nGram
                                min_gram: 1
                                max_gram: 20
            types:
                strain:
                    mappings:
                        discriminator:
                        autoName:
                            analyzer :        ngram_index_analyzer
                            search_analyzer : search_analyzer
                        name:
                            analyzer :        ngram_index_analyzer
                            search_analyzer : search_analyzer
                        country:
                        author_id:
                            property_path:    author.id
                        deleted:
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\Strain
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             ~
                plasmid:
                    mappings:
                        autoName:
                            analyzer :        ngram_index_analyzer
                            search_analyzer : search_analyzer
                        name:
                            analyzer :        ngram_index_analyzer
                            search_analyzer : search_analyzer
                            type:             string
                        name_raw:
                            type:             string
                            index:            not_analyzed
                            property_path:    name
                        team_id:
                            property_path:    team.id
                        author_id:
                            property_path:    author.id
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\Plasmid
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             AppBundle\SearchRepository\PlasmidRepository
                primer:
                    mappings:
                        autoName:
                            analyzer :        ngram_index_analyzer
                            search_analyzer : search_analyzer
                        name:
                            analyzer :        ngram_index_analyzer
                            search_analyzer : search_analyzer
                        name_raw:
                            type:             string
                            index:            not_analyzed
                            property_path:    name
                        team_id:
                            property_path:    team.id
                        author_id:
                            property_path:    author.id
                        sequence:
                            analyzer :        ngram_sequence_analyzer
                            search_analyzer : search_analyzer
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\Primer
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             AppBundle\SearchRepository\PrimerRepository
                species:
                    mappings:
                        name:
                            analyzer :        ngram_index_analyzer
                            search_analyzer : search_analyzer
                            property_path:    scientificName
                        name_raw:
                            type:             string
                            index:            not_analyzed
                            property_path:    scientificName
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\Species
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             AppBundle\SearchRepository\SpeciesRepository
                      elastica_to_model_transformer:
                        query_builder_method: createSearchQueryBuilder
                type:
                    mappings:
                        name:
                            analyzer :        ngram_index_analyzer
                            search_analyzer : search_analyzer
                            property_path:    name
                        name_raw:
                            type:             string
                            index:            not_analyzed
                            property_path:    name
                        team_id:
                            property_path:    team.id
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\Type
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             AppBundle\SearchRepository\TypeRepository
                biologicalOriginCategory:
                    mappings:
                        name:
                            analyzer :        ngram_index_analyzer
                            search_analyzer : search_analyzer
                            property_path:    name
                        name_raw:
                            type:             string
                            index:            not_analyzed
                            property_path:    name
                        team_id:
                            property_path:    team.id
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\BiologicalOriginCategory
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             AppBundle\SearchRepository\BiologicalOriginCategoryRepository
                project:
                    mappings:
                        name:
                            analyzer :        ngram_index_analyzer
                            search_analyzer : search_analyzer
                            property_path:    name
                        name_raw:
                            type:             string
                            index:            not_analyzed
                            property_path:    name
                        team_id:
                            property_path:    team.id
                        members_id:
                            property_path:    membersId
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\Project
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             AppBundle\SearchRepository\ProjectRepository
                box:
                    mappings:
                        autoName:
                            analyzer :        ngram_index_analyzer
                            search_analyzer : search_analyzer
                        name:
                            analyzer :        ngram_index_analyzer
                            search_analyzer : search_analyzer
                        autoName_raw:
                            type:             string
                            index:            not_analyzed
                            property_path:    autoName
                        name_raw:
                            type:             string
                            index:            not_analyzed
                            property_path:    name
                        description:
                            analyzer :        ngram_index_analyzer
                            search_analyzer : search_analyzer
                        project:
                            analyzer :        ngram_index_analyzer
                            search_analyzer : search_analyzer
                            property_path:    project
                        project_id:
                            property_path:    project.id
                    persistence:
                      driver:                 orm
                      model:                  AppBundle\Entity\Box
                      provider:               ~
                      listener:               ~
                      finder:                 ~
                      repository:             AppBundle\SearchRepository\BoxRepository
