# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        public:    false
        tags:
            - { name: twig.extension }

    app.form_type.tube:
        class: AppBundle\Form\TubeType
        arguments: ["@doctrine.orm.entity_manager"]
        tags: [{ name: form.type }]
