# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
# Twig extensions
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        public:    false
        tags:
            - { name: twig.extension }

    app.twig.country_extension:
        class: AppBundle\Twig\CountryExtension
        tags:
            - { name: twig.extension }

    app.twig.plasmid_extension:
        class: AppBundle\Twig\PlasmidExtension
        tags:
            - { name: twig.extension }

# Form
    app.type.genus_selector:
        class: AppBundle\Form\Type\GenusSelectorType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }

    app.form_type.tube:
        class: AppBundle\Form\Type\TubeType
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]
        tags:
            - { name: form.type }

    app.form_type.strain:
        class: AppBundle\Form\Type\StrainType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    app.form_type.box:
        class: AppBundle\Form\Type\BoxType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type }

    app.form_type.plasmid:
        class: AppBundle\Form\Type\PlasmidType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type }

    app.form_type.advanced_search:
        class: AppBundle\Form\Type\AdvancedSearchType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type }

# Listeners
    app.event_listener.species:
        class: AppBundle\EventListener\SpeciesListener
        tags:
            - { name: doctrine.event_listener, event: postRemove }

    app.event_listener.strain:
        class: AppBundle\EventListener\StrainSubscriber
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_subscriber }

    app.event_listener.team:
        class: AppBundle\EventListener\TeamListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    app.event_listener.search.strain:
        class: AppBundle\EventListener\StrainSearchIndexListener
        tags:
            - { name: kernel.event_subscriber }

# Voters
    app.voter.project:
        class: AppBundle\Security\ProjectVoter
        arguments: ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        # small performance boost
        public: false

    app.voter.box:
        class: AppBundle\Security\BoxVoter
        arguments: ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        public: false

    app.voter.strain:
        class: AppBundle\Security\StrainVoter
        arguments: ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        public: false

    app.voter.plasmid:
        class: AppBundle\Security\PlasmidVoter
        arguments: ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        public: false
