# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
# Twig extensions
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        public:    false
        tags:
            - { name: twig.extension }

    app.twig.country_extension:
        class: AppBundle\Twig\CountryExtension
        tags:
            - { name: twig.extension }

    app.twig.plasmid_extension:
        class: AppBundle\Twig\PlasmidExtension
        tags:
            - { name: twig.extension }

# Form
    app.form_type.tube:
        class: AppBundle\Form\TubeType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    app.form_type.strain:
        class: AppBundle\Form\StrainType
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]
        tags:
            - { name: form.type }

    app.form_type.wild_strain:
        class: AppBundle\Form\WildStrainType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type }

    app.form_type.type:
        class: AppBundle\Form\TypeType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type }

    app.form_type.box:
        class: AppBundle\Form\BoxType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type }

    app.form_type.biological_origin_category:
        class: AppBundle\Form\BiologicalOriginCategoryType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type }

    app.form_type.plasmid:
        class: AppBundle\Form\PlasmidType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type }

# Listeners
    app.event_listener.strain:
        class: AppBundle\EventListener\StrainListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    app.event_listener.team:
        class: AppBundle\EventListener\TeamListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    app.event_listener.search.strain_authorized_team:
        class: AppBundle\EventListener\StrainAuthorizedTeamListener
        tags:
            - { name: kernel.event_subscriber }

# Voters
    app.voter.project:
        class: AppBundle\Security\ProjectVoter
        arguments: ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        # small performance boost
        public: false

    app.voter.strain:
        class: AppBundle\Security\StrainVoter
        arguments: ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        public: false

    app.voter.type:
        class: AppBundle\Security\TypeVoter
        arguments: ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        public: false

    app.voter.biological_origin_category:
        class: AppBundle\Security\BiologicalOriginCategoryVoter
        arguments: ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        public: false
